# -*- coding: utf-8 -*-
"""speech_recogn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZpfw1xkzuTgukzjMR4lkM74YoOUtbXm
"""

import os
import pathlib
import numpy as np
import librosa
import tensorflow as tf
from tensorflow.keras import layers, models
from sklearn.model_selection import train_test_split
from IPython.display import Audio

# --- Configuration for Target Words and Feature Extraction ---
TARGET_COMMANDS = ['yes', 'no', 'up', 'down', 'on', 'off']
SILENCE_LABEL = '_silence_'
UNKNOWN_LABEL = '_unknown_'
# All classes the model will predict, including non-target words and silence
ALL_LABELS = TARGET_COMMANDS + [UNKNOWN_LABEL, SILENCE_LABEL]
NUM_CLASSES = len(ALL_LABELS)

# Audio Parameters
SAMPLE_RATE = 16000
CLIP_DURATION_S = 1.0
SAMPLES_TO_PAD = int(SAMPLE_RATE * CLIP_DURATION_S)

# MFCC Parameters for fixed-size 2D input
N_MFCC = 13          # Number of coefficients (frequency axis size)
N_FFT = 2048         # FFT window size
HOP_LENGTH = 512     # Frame hop size (determines time axis size)
TARGET_TIME_STEPS = 32 # The desired number of time steps (frames)

def compute_mfcc(audio_data):
    """
    Computes MFCCs from an audio array, padding/truncating to a fixed size
    (TARGET_TIME_STEPS, N_MFCC).
    """
    # 1. Ensure fixed length (1.0s clip)
    if len(audio_data) < SAMPLES_TO_PAD:
        padding = SAMPLES_TO_PAD - len(audio_data)
        audio_data = np.pad(audio_data, (0, padding), mode='constant')
    elif len(audio_data) > SAMPLES_TO_PAD:
        audio_data = audio_data[:SAMPLES_TO_PAD]

    # 2. Compute MFCCs
    # Note: Using n_mels=40 is a common practice in keyword spotting
    mfccs = librosa.feature.mfcc(
        y=audio_data.astype(float),
        sr=SAMPLE_RATE,
        n_mfcc=N_MFCC,
        n_fft=N_FFT,
        hop_length=HOP_LENGTH,
        n_mels=40
    )

    # Transpose to get a time-major matrix: [Time Steps, MFCC Coeffs]
    mfccs = mfccs.T

    # 3. Ensure target time steps (for consistent CNN input)
    if mfccs.shape[0] < TARGET_TIME_STEPS:
        padding = TARGET_TIME_STEPS - mfccs.shape[0]
        mfccs = np.pad(mfccs, ((0, padding), (0, 0)), mode='constant')
    elif mfccs.shape[0] > TARGET_TIME_STEPS:
        mfccs = mfccs[:TARGET_TIME_STEPS, :]

    return mfccs

# --- Download Data (Mini Speech Commands Dataset) ---
data_dir = pathlib.Path('/content/data/mini_speech_commands_extracted/mini_speech_commands')

if not data_dir.exists():
    print("Downloading dataset...")
    tf.keras.utils.get_file(
        'mini_speech_commands.zip',
        origin='http://storage.googleapis.com/download.tensorflow.org/data/mini_speech_commands.zip',
        extract=True,
        cache_dir='.',
        cache_subdir='data'
    )

# --- 3.1. Map all files to their label and path ---
all_files = []
all_labels_text = []

# Mini Speech Commands includes 'yes', 'no', 'up', 'down', 'left', 'right', 'on', 'off', 'stop', 'go'
word_folders = [d for d in data_dir.iterdir() if d.is_dir() and str(d.name) != '_background_noise_']

for word_folder in word_folders:
    label_name = word_folder.name

    for file in word_folder.glob('*.wav'):
        all_files.append(str(file))

        # Supervised Learning Classification
        if label_name in TARGET_COMMANDS:
             all_labels_text.append(label_name)
        else:
             # Words not in TARGET_COMMANDS (like 'stop', 'go', 'left', 'right') become UNKNOWN
             all_labels_text.append(UNKNOWN_LABEL)

# Create numeric labels
label_to_index = {label: index for index, label in enumerate(ALL_LABELS)}
all_label_indices = np.array([label_to_index[label] for label in all_labels_text])

print(f"Total audio files found: {len(all_files)}")
print(f"Target Classes (and indices): {label_to_index}")

# --- 3.2. Generate MFCC Features ---
X_mfcc = []
Y_labels = []

print("\nStarting MFCC feature generation...")
for i, (file_path, label_index) in enumerate(zip(all_files, all_label_indices)):
    if i % 1000 == 0 and i > 0:
        print(f"Processed {i} files...")

    try:
        # Load audio with the configured sample rate
        audio_data, _ = librosa.load(file_path, sr=SAMPLE_RATE)
        mfccs = compute_mfcc(audio_data)

        # Only add if the shape is correct
        if mfccs.shape == (TARGET_TIME_STEPS, N_MFCC):
            X_mfcc.append(mfccs)
            Y_labels.append(label_index)

    except Exception as e:
        # print(f"Skipping file {file_path} due to error: {e}")
        continue

X_mfcc = np.array(X_mfcc)
Y_labels = np.array(Y_labels)

# --- 3.3. Split the Dataset (80/10/10) ---
# Split 1: 80% Train, 20% Temp (Val/Test)
X_train, X_temp, Y_train, Y_temp = train_test_split(
    X_mfcc, Y_labels, test_size=0.2, random_state=42, stratify=Y_labels
)

# Split 2: 20% Temp into 10% Validation, 10% Test
X_val, X_test, Y_val, Y_test = train_test_split(
    X_temp, Y_temp, test_size=0.5, random_state=42, stratify=Y_temp
)

# Add the channel dimension for the CNN (required input format: [samples, height, width, 1])
X_train = X_train[..., np.newaxis]
X_val = X_val[..., np.newaxis]
X_test = X_test[..., np.newaxis]

print(f"\n--- Final Processed Shapes ---")
print(f"MFCC Input Shape (Time Steps, Coeffs, Channel): {X_train.shape[1:]}")
print(f"Training Samples: {X_train.shape[0]} | Validation Samples: {X_val.shape[0]} | Test Samples: {X_test.shape[0]}")

def build_tinyconv_model(input_shape, num_classes):
    """Defines a small Convolutional Neural Network (TinyConv)."""
    model = models.Sequential([
        # Input layer expects the MFCC feature 'image'
        layers.Input(shape=input_shape),

        # Block 1
        layers.Conv2D(16, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.2),

        # Block 2
        layers.Conv2D(32, (3, 3), activation='relu', padding='same'),
        layers.MaxPooling2D((2, 2)),
        layers.Dropout(0.2),

        # Classifier Head
        layers.Flatten(),
        layers.Dense(64, activation='relu'),
        layers.Dropout(0.5),
        layers.Dense(num_classes, activation='softmax') # Output for the 8 classes
    ])

    return model

# Build the model
input_shape = X_train.shape[1:]
model = build_tinyconv_model(input_shape, NUM_CLASSES)

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy', # Used because labels (Y) are integers
    metrics=['accuracy']
)

print("--- Model Summary ---")
model.summary()

# --- Model Training ---
EPOCHS = 75
BATCH_SIZE = 32

print("\nStarting Model Training...")
history = model.fit(
    X_train,
    Y_train,
    validation_data=(X_val, Y_val),
    epochs=EPOCHS,
    batch_size=BATCH_SIZE,
    # Stop training early if validation loss doesn't improve for 5 epoch
)

# --- Evaluate on Test Set and Save ---
loss, accuracy = model.evaluate(X_test, Y_test, verbose=0)
print(f"\n✅ Training Complete. Test Accuracy: {accuracy*100:.2f}%")

# Save the trained Keras model (HDF5 format)
model.save('tinyconv_kws_model.h5')
print("Model saved to tinyconv_kws_model.h5")

from google.colab import files
from tensorflow.keras.models import load_model
import librosa
import numpy as np

# --- 1. Load the Model and Configuration ---

# These must match the variables in your training cells (Cell 2) exactly!
ALL_LABELS = ['yes', 'no', 'up', 'down', 'on', 'off', '_unknown_', '_silence_']
SAMPLE_RATE = 16000
N_MFCC = 13
TARGET_TIME_STEPS = 32
CLIP_DURATION_S = 1.0
SAMPLES_TO_PAD = int(SAMPLE_RATE * CLIP_DURATION_S)

try:
    # Load the trained model saved in the previous step
    model = load_model('tinyconv_kws_model.h5')
    print("Model 'tinyconv_kws_model.h5' loaded successfully.")
except Exception as e:
    print(f"Error loading model: {e}")
    print("Please ensure your training cell (Cell 4) was run and the model was saved.")


# --- 2. Re-define the MFCC Function (Crucial) ---

# Re-defining the function here ensures it's available, even if you run this
# cell without re-running Cell 2.

def compute_mfcc(audio_data):
    """Computes MFCCs from an audio array, padding/truncating to fixed size."""

    # Ensure fixed length (1.0s clip)
    if len(audio_data) < SAMPLES_TO_PAD:
        padding = SAMPLES_TO_PAD - len(audio_data)
        audio_data = np.pad(audio_data, (0, padding), mode='constant')
    elif len(audio_data) > SAMPLES_TO_PAD:
        audio_data = audio_data[:SAMPLES_TO_PAD]

    # Use the same parameters as training
    N_FFT = 2048
    HOP_LENGTH = 512
    N_MELS = 40

    mfccs = librosa.feature.mfcc(
        y=audio_data.astype(float),
        sr=SAMPLE_RATE,
        n_mfcc=N_MFCC,
        n_fft=N_FFT,
        hop_length=HOP_LENGTH,
        n_mels=N_MELS
    )

    mfccs = mfccs.T

    # Ensure target time steps
    if mfccs.shape[0] < TARGET_TIME_STEPS:
        padding = TARGET_TIME_STEPS - mfccs.shape[0]
        mfccs = np.pad(mfccs, ((0, padding), (0, 0)), mode='constant')
    elif mfccs.shape[0] > TARGET_TIME_STEPS:
        mfccs = mfccs[:TARGET_TIME_STEPS, :]

    return mfccs

# Use the file uploader widget in Colab
print("Please upload your 1-second WAV audio file (or any WAV file):")
uploaded = files.upload()

# Get the name of the uploaded file
audio_filename = list(uploaded.keys())[0]

# --- 1. Load Audio ---
try:
    # librosa loads the audio and resamples it to 16000 Hz automatically
    waveform, sr = librosa.load(audio_filename, sr=SAMPLE_RATE)
except Exception as e:
    print(f"Error loading audio file: {e}")

# --- 2. Pre-process (MFCC Feature Extraction) ---
# Your audio must be converted to the exact features the model was trained on
mfccs = compute_mfcc(waveform)

# Reshape for the model: Add batch dimension (1) and channel dimension (1)
# Input shape: (32, 13) -> (1, 32, 13, 1)
mfccs_input = mfccs[np.newaxis, ..., np.newaxis]

print(f"\nProcessed MFCC input shape: {mfccs_input.shape}")

# --- 3. Run Inference ---
predictions = model.predict(mfccs_input, verbose=0)
# Get the index of the class with the highest probability
predicted_index = np.argmax(predictions[0])

# --- 4. Get Result ---
predicted_label = ALL_LABELS[predicted_index]
confidence = predictions[0][predicted_index]

print("\n--- 🎤 CLASSIFICATION RESULT ---")
print(f"File: {audio_filename}")
print(f"Predicted Command: **{predicted_label.upper()}**")
print(f"Confidence: {confidence * 100:.2f}%")

# Display all probabilities
print("\nProbabilities for all classes:")
for label, prob in zip(ALL_LABELS, predictions[0]):
    print(f"  {label.ljust(10)}: {prob * 100:.2f}%")